config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :videos
  resources :users
  get 'sessions/new'

  root 'static_pages#home'
  get 'cv' => 'static_pages#cv'
  get 'kitty' => 'static_pages#kitty'
  get 'game' => 'static_pages#game'

  get 'photo' => 'photos#index'
  get 'new_photo' => 'photos#new'
  get 'delete_photo' => 'photos#delete'
  get 'photoplay' => 'photos#play'

  get 'videos' => 'videos#index'

  get 'signup' => 'users#new'
  get 'users' => 'users#index'
  get 'edit' => 'users#edit'

  get 'login' => 'sessions#new'
  post 'login'=> 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/video.rb
class Video < ActiveRecord::Base
validates :link, presence: true, uniqueness: { case_sensitive: true }, format: { with: /\Ahttps:\/\/www\.youtube\.com\/watch\?v=+.*\z/ }
  belongs_to :user
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_action :admin_user, only: [:destroy]
  before_action :logged_in_user

  def index
    @playlist = Video.where(isPlaylist: true).order(created_at: :desc)
    @videos = Video.where(isPlaylist: false).order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def create
    @video = current_user.videos.build(video_params) if logged_in?
    if @video.save
      flash[:success] = "The video was added!"
      redirect_to videos_path
    else
      render 'new'
    end
  end

  def new
    @video = Video.new
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    flash[:success] = "The video was destroyed."
    redirect_to videos_path
  end

  private

  def video_params
    params.require(:video).permit(:link, :isPlaylist)
  end

end

app/helpers/videos_helper.rb
module VideosHelper
  #return videos
  def getLinkedVideo(video)
    $videolink = video.link
    #https:\/\/www.youtube.com\/watch\?v=(.*)
    $videolinkParse = $videolink.match('https:\/\/www.youtube.com\/watch\?v=(.*)')
    if  !$videolinkParse.nil?
     li ='<iframe width="560" height="315" src="https://www.youtube.com/embed/' + $videolinkParse[1] + '" allowfullscreen></iframe>'
    else
     li =''
    end
    return li.html_safe
  end

end

app/views/videos/index.html.erb
<% provide(:title,"Musique") %>
<h1>Musique</h1>
<script>
function showDeleteButton(){
  $(".removeVideo").css('display', 'block');
}
</script>
<div class="videos">
  <% @playlist.each do |playlist| %>
  <%= getLinkedVideo(playlist) %>
  <br />
  <%= link_to 'Remove', video_path(playlist), class: 'btn btn-danger removeVideo',
  method: :delete %>
  <% end %>
  <hr>
  <%= will_paginate @videos, renderer: BootstrapPagination::Rails %>
  <br />
  <% @videos.each do |video| %>
  <%= getLinkedVideo(video) %>
  <br />
  <%= link_to 'Remove', video_path(video), class: 'btn btn-danger removeVideo',
  method: :delete %>
  <% end %>
  <%= will_paginate @videos, renderer: BootstrapPagination::Rails %>
</div>
<div class="row">
  <% if current_user.admin? %>
  <div class="col-xs-6">
    <% else %>
    <div class="col-xs-12">
      <% end %>
      <button type="button" class="btn btn-success btn-circle btn-lg" data-toggle="tooltip" data-placement="top" title="Upload Photos">
        <%= link_to new_video_path, class: 'button alt' do %>
        <i class="glyphicon glyphicon-upload"></i>
        <% end %>
      </button>
    </div>

    <% if current_user.admin? %>
    <div class="col-xs-6">
      <button type="button" onclick='showDeleteButton()' class="btn btn-danger btn-circle btn-lg" data-toggle="tooltip" data-placement="top" title="Remove Photos">
        <i class="glyphicon glyphicon-remove"></i>
      </button>
    </div>
    <% end %>
  </div>

app/views/videos/new.html.erb
<% provide(:title,"Musique") %>
<h1>Musique</h1>
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
<%= form_for @video do |f| %>
  <%= render 'layouts/errors', object: @video %>
  <div class="form-group">
    <%= f.url_field :link, class: 'form-control' %>
  </div>
  <%= f.submit 'Upload', class: 'btn btn-primary' %>
  <%= f.label :isPlaylist, class: "checkbox" do %>
    <%= f.check_box :isPlaylist %>
    This Video is a playlist
    <% end %>
    <% end %>
    </div>
</div>