config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :videos
  resources :users
  get 'sessions/new'

  root 'static_pages#home'
  get 'cv' => 'static_pages#cv'
  get 'kitty' => 'static_pages#kitty'
  get 'game' => 'static_pages#game'

  get 'photo' => 'photos#index'
  get 'new_photo' => 'photos#new'
  get 'delete_photo' => 'photos#delete'
  get 'photoplay' => 'photos#play'

  get 'videos' => 'videos#index'

  get 'signup' => 'users#new'
  get 'users' => 'users#index'
  get 'edit' => 'users#edit'

  get 'login' => 'sessions#new'
  post 'login'=> 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle"
      data-toggle="collapse"
      data-target=".navbar-collapse">
      <span class="sr-only">Toggle
        navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Waiting for the plane to land",
      root_path, id:"logo" %>
    </div>
    <nav class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">        
        <% if !logged_in? %>
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Accueil",   root_path %></li>
        <li class="<%= 'active' if current_page?(cv_path) %>"><%= link_to "CV", cv_path %></li>
        <% end %>
        <% if logged_in? %>
        <li class="<%= 'active' if current_page?(photos_path) %>"><%= link_to "Photos",   photos_path %></li>
        <li class="<%= 'active' if current_page?(photoplay_path) %>"><%= link_to "Photoplay", photoplay_path %></li>
        <li class="<%= 'active' if current_page?(videos_path) %>"><%= link_to "Musique",   videos_path %></li>
        <% end %>
        <li class="<%= 'active' if current_page?(kitty_path) %>"><%= link_to "Kitty",  kitty_path %></li>
        <li class="<%= 'active' if current_page?(game_path) %>"><%= link_to "Game",  game_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
            <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Users", users_path %></li>
            <li class="<%= 'active' if current_page?(signup_path) %>"><%= link_to "Sign up", signup_path %></li>
            <li class="<%= 'active' if current_page?(cv_path) %>"><%= link_to "CV", cv_path %></li>
            <% end %>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li class="<%= 'active' if current_page?(login_path) %>"><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="jumbotron center">
    <br />
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>